# Generated by Django 5.0.4 on 2024-05-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Proprety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=31)),
                ('description', models.CharField(max_length=31)),
                ('size', models.FloatField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=31)),
                ('adresse', models.CharField(max_length=31)),
                ('phone_number', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prix', models.FloatField()),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('property_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.proprety')),
            ],
        ),
        migrations.CreateModel(
            name='RentalUnity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_number', models.FloatField()),
                ('monthly_rent', models.FloatField()),
                ('property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.proprety')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=31)),
                ('payment_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.rentalunity')),
                ('payment_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(max_length=31)),
                ('unit_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.rentalunity')),
                ('tenant_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('deposit_amount', models.FloatField()),
                ('tenant_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.tenant')),
            ],
        ),
    ]
